version: "3.3"
services:
  reddit-bot:
    container_name: 'reddit-bot'
    command: bash -c "jupyter lab --notebook-dir=/home/reddit-bot --ip='0.0.0.0' --port=8888 --no-browser --allow-root"
    build: .
    ports:
      - '8888:8888'
    volumes:
      - ../:/home/reddit-bot